version: "3"
services:
  db:
    restart: unless-stopped
    image: postgres
    container_name: "food_box-database"
    environment:
      POSTGRES_USER: foodbox
      POSTGRES_PASSWORD: foodbox
      POSTGRES_DB: foodbox
    ports:
      - 54320:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  phpPgAdmin:
    restart: unless-stopped
    container_name: "phppgadmin"
    image: dockage/phppgadmin
    environment:
    - PHP_PG_ADMIN_SERVER_HOST=db
    - PHP_PG_ADMIN_SERVER_PORT=5432
    - PHP_PG_ADMIN_SERVER_DEFAULT_DB=foodbox
    - PHP_PG_ADMIN_EXTRA_LOGIN_SECURITY=true
    ports:
    - 30000:80
    links:
    - db