spring:
  datasource:
    url: jdbc:postgresql://localhost:54320/foodbox
    username: foodbox
    password: foodbox
  jpa:
    show-sql: false
    hibernate.ddl-auto: validate
    open-in-view: false
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      temp.use_jdbc_metadata_defaults: false
  main.lazy-initialization: true

  liquibase:
    change-log: classpath:/db.changelog-master.xml

server.error.whitelabel.enabled: false